/*
 * Copyright (C) 2017 Piotr Martycz
 */
package etest.gui;

import etest.entities.Test;
import etest.entities.TestStatus;
import java.awt.event.ActionListener;
import javax.swing.AbstractButton;

/**
 *
 * @author pmart
 */
public class AnswersPanel extends javax.swing.JPanel {
    private Test test;
    private int questionIndex;

    /**
     * Creates new form AnswersPanel
     */
    public AnswersPanel(Test test, int questionIndex) {
        initComponents();
        
        this.test = test;
        this.questionIndex = questionIndex;
  
        createButtons();
    }

    private final void createButtons() {
        AbstractButton btn;
        AbstractButtonFactory buttonFactory = AbstractButtonFactory.getFactory(test.getType());
        String[] questionOptions = test.getQuestionOptions(questionIndex);
        ActionListener actionListener = e -> test.setQuestionOption(questionIndex, 
                        Integer.parseInt(e.getActionCommand()), 
                        ((AbstractButton) e.getSource()).isSelected());
        
        for (int i = 0; i < questionOptions.length; i++) {
            btn = buttonFactory.make();
            btn.setText(questionOptions[i]);
            btn.setSelected(test.isQuestionOptionSelected(questionIndex, i));
            if (test.isStatus(TestStatus.PENDING)) {
                btn.setActionCommand(Integer.toString(i));
                btn.addActionListener(actionListener);
            } else {
                btn.setEnabled(false);
            }
            add(btn);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
